-- Create ai_voices table
CREATE TABLE public.ai_voices (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  voice_id text null,
  name text null,
  provider text null,
  constraint ai_voices_pkey primary key (id)
) TABLESPACE pg_default;

-- Enable Row Level Security (RLS)
ALTER TABLE public.ai_voices ENABLE ROW LEVEL SECURITY;

-- Create policy to allow authenticated users to read voices
CREATE POLICY "Users can view ai_voices" ON public.ai_voices
FOR SELECT TO authenticated
USING (true);

-- Create policy to allow admin users to manage voices
CREATE POLICY "Admin users can manage ai_voices" ON public.ai_voices
FOR ALL TO authenticated
USING (auth.jwt() ->> 'role' = 'admin');

-- Create index for better performance on provider filtering
CREATE INDEX idx_ai_voices_provider ON public.ai_voices(provider);
CREATE INDEX idx_ai_voices_voice_id ON public.ai_voices(voice_id); 